- name: frontend setup
  hosts: all
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Copy file of expense conf
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf &>>/tmp/expense.log

    - name: enable nginx
      ansible.builtin.service:
        name: nginx
        state: started