- name: disable nodejs -y
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs:20
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: add user expense
  ansible.builtin.user:
    name: expense

- name: import app pre req
  ansible.builtin.import_role:
      name: common
      tasks_from: app pre req

- name: download nodejs dependency
  community.general.npm:
    path: /app
    state: latest

- name: copy backend service file
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: install python mysql client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    state: pip3.9
    state: latest


- name: load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.janand.online

- name: start backend
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: yes
    daemon_reload: yes
    restart: yes
