
- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy file of expense conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: import app pre req
  ansible.builtin.import_role:
    name: common
    tasks_from: app pre req

- name: Restart Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enable: yes

