
- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy file of expense conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Ensure Nginx service is started
  systemd:
    name: nginx
    state: started
    daemon_reload: yes
    no_block: yes
    enabled: yes
  become: yes
  become_user: root
  tags:
    - nginx


- name: import app pre req
  ansible.builtin.import_role:
    name: common
    tasks_from: app pre req

- name: Ensure Nginx service is started
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    no_block: yes
    enabled: yes
  become: yes
  become_user: root
  tags:
    - nginx


